### ISSUE TITLE
Add "compensatory time" + "doctor visit" leave type

### ISSUE THREAD

**Issue by sodik82** [instea/Cestovne-prikazy#24]
* this should not count as vacation day!

**Comment by misosviso** [comment]
Mam sem priradit nejaky mapping pre ten "compensatory time"?
![image](https://user-images.githubusercontent.com/56072239/218517392-2a25a85c-9ce6-4140-bc14-d5788b4b46c8.png)

**Comment by sodik82** [comment]
a vies co, nechaj tak... nahradne volno sa aj tak riesi v ramci mesiaca, cize je to jedno...
