### ISSUE TITLE
Internship workspace

### ISSUE THREAD

**Issue by jansvantner** [instea/Cestovne-prikazy#64]
Since we have Normal & Internship workspaces we'll need to download data from both of them.
Normal: https://track.toggl.com/2108957/team/members
Internship: https://track.toggl.com/4785862/team/members

**Comment by JozefKamensky** [comment]
Data are downloaded for each user defined in SSO Metadata using keys:
* employee (only for employee == 1)
* _togglWorkspaceId_
* _togglUserId_
* _togglApiToken_

so only correct setup of keys in SSO Metadata is needed to collect data from various Toggl workspaces.
