### ISSUE TITLE
Check how leaves are reported through API

### ISSUE THREAD

**Issue by sodik82** [instea/Cestovne-prikazy#68]
check if vacation over weekend (or public holiday) is correctly reported.

**Comment by JozefKamensky** [comment]
Do you have an example of erroneous report ? If yes, please post it.

**Comment by sodik82** [comment]
These are the data from other app using the API:

![image](https://user-images.githubusercontent.com/6132259/123937880-ea0d6400-d996-11eb-98c7-6a68eaff3c01.png)

i.e. reporting `D8` (full anual vacation) also for Sat-Sun. 

I am not familiar with exact API nor the other app itself - thus I am suggesting to check the over-weekend vacation reporting case.

**Comment by JozefKamensky** [comment]
Current implementation marks every day between start and end of vacation as vacation day (including weekends or public holidays). Change it to not include weekends is easy, problem could be with public holidays (if there is no usable library for it).

**Comment by jurajmatus** [comment]
I don't know what API is provided by the application, but the core mechanism already counts with weekends and public holidays:
![tmp jXGpRR2Whr](https://user-images.githubusercontent.com/17612051/123940025-10340380-d999-11eb-8770-adfbfd028164.png)

Proper reuse of that code should do the trick.

**Comment by sodik82** [comment]
UI already accounts these...

![image](https://user-images.githubusercontent.com/6132259/123940217-3a85c100-d999-11eb-9b6a-9f238f940518.png)

example with weekend and public holiday.  (there is some 3rd party library used)
